//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/linklayer/ieee80211/mgmt/Ieee80211BdPrimitives.msg.
//

#ifndef __INET__IEEE80211_IEEE80211BDPRIMITIVES_M_H
#define __INET__IEEE80211_IEEE80211BDPRIMITIVES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace ieee80211 {

class MlmeRadioEnvironmentRequest;
class MlmeRadioEnvironmentIndication;
class NgvRadioEnvironmentRequestVector;
class MaUnitdataRequest;
class MaUnitdataIndication;
class MaUnitdataStatusIndication;

}  // namespace ieee80211
}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/linklayer/common/MacAddress_m.h" // import inet.linklayer.common.MacAddress


namespace inet {
namespace ieee80211 {

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mgmt/Ieee80211BdPrimitives.msg:22</tt> by opp_msgtool.
 * <pre>
 * class MlmeRadioEnvironmentRequest extends cObject
 * {
 *     int radioEnvironmentMeasurementPeriod;   // 0, 100–1000 ms
 *     int stationMeasurementPeriod;            // 0, 100–1000 ms
 * }
 * </pre>
 */
class INET_API MlmeRadioEnvironmentRequest : public ::omnetpp::cObject
{
  protected:
    int radioEnvironmentMeasurementPeriod = 0;
    int stationMeasurementPeriod = 0;

  private:
    void copy(const MlmeRadioEnvironmentRequest& other);

  protected:
    bool operator==(const MlmeRadioEnvironmentRequest&) = delete;

  public:
    MlmeRadioEnvironmentRequest();
    MlmeRadioEnvironmentRequest(const MlmeRadioEnvironmentRequest& other);
    virtual ~MlmeRadioEnvironmentRequest();
    MlmeRadioEnvironmentRequest& operator=(const MlmeRadioEnvironmentRequest& other);
    virtual MlmeRadioEnvironmentRequest *dup() const override {return new MlmeRadioEnvironmentRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getRadioEnvironmentMeasurementPeriod() const;
    virtual void setRadioEnvironmentMeasurementPeriod(int radioEnvironmentMeasurementPeriod);

    virtual int getStationMeasurementPeriod() const;
    virtual void setStationMeasurementPeriod(int stationMeasurementPeriod);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MlmeRadioEnvironmentRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MlmeRadioEnvironmentRequest& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mgmt/Ieee80211BdPrimitives.msg:28</tt> by opp_msgtool.
 * <pre>
 * class MlmeRadioEnvironmentIndication extends cObject
 * {
 *     int stationCount;                // 0–65535
 *     int ngvCapabilityPercentage;     // 0–100
 *     int channelBusyPercentage;       // 0–100
 * }
 * 
 * //
 * // NGV Radio Environment Request Vector (Clause 31.5)
 * //
 * </pre>
 */
class INET_API MlmeRadioEnvironmentIndication : public ::omnetpp::cObject
{
  protected:
    int stationCount = 0;
    int ngvCapabilityPercentage = 0;
    int channelBusyPercentage = 0;

  private:
    void copy(const MlmeRadioEnvironmentIndication& other);

  protected:
    bool operator==(const MlmeRadioEnvironmentIndication&) = delete;

  public:
    MlmeRadioEnvironmentIndication();
    MlmeRadioEnvironmentIndication(const MlmeRadioEnvironmentIndication& other);
    virtual ~MlmeRadioEnvironmentIndication();
    MlmeRadioEnvironmentIndication& operator=(const MlmeRadioEnvironmentIndication& other);
    virtual MlmeRadioEnvironmentIndication *dup() const override {return new MlmeRadioEnvironmentIndication(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getStationCount() const;
    virtual void setStationCount(int stationCount);

    virtual int getNgvCapabilityPercentage() const;
    virtual void setNgvCapabilityPercentage(int ngvCapabilityPercentage);

    virtual int getChannelBusyPercentage() const;
    virtual void setChannelBusyPercentage(int channelBusyPercentage);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MlmeRadioEnvironmentIndication& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MlmeRadioEnvironmentIndication& obj) {obj.parsimUnpack(b);}

/**
 * Enum generated from <tt>inet/linklayer/ieee80211/mgmt/Ieee80211BdPrimitives.msg:39</tt> by opp_msgtool.
 * <pre>
 * enum NgvPpduFormat
 * {
 *     NON_NGV_10 = 0;
 *     NGV = 1;
 * }
 * </pre>
 */
enum NgvPpduFormat {
    NON_NGV_10 = 0,
    NGV = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NgvPpduFormat& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NgvPpduFormat& e) { int n; b->unpack(n); e = static_cast<NgvPpduFormat>(n); }

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mgmt/Ieee80211BdPrimitives.msg:45</tt> by opp_msgtool.
 * <pre>
 * class NgvRadioEnvironmentRequestVector extends cObject
 * {
 *     NgvPpduFormat ppduFormat;
 * 
 *     int ngvMcs;
 *     int numSpatialStreams;
 *     bool permittedAggregation;
 * 
 *     int numRepetitions;
 *     simtime_t expiryTime; // lifetime으로 수정필요
 * 
 *     int channelNumber;
 *     int primaryChannelNumber;
 *     int channelWidth;  // MHz
 * 
 *     double txPowerSpectralDensity;
 * }
 * 
 * //
 * // MA-UNITDATA (NGV MAC data service 확장)
 * //
 * </pre>
 */
class INET_API NgvRadioEnvironmentRequestVector : public ::omnetpp::cObject
{
  protected:
    NgvPpduFormat ppduFormat = static_cast<inet::ieee80211::NgvPpduFormat>(-1);
    int ngvMcs = 0;
    int numSpatialStreams = 0;
    bool permittedAggregation = false;
    int numRepetitions = 0;
    ::omnetpp::simtime_t expiryTime = SIMTIME_ZERO;
    int channelNumber = 0;
    int primaryChannelNumber = 0;
    int channelWidth = 0;
    double txPowerSpectralDensity = 0;

  private:
    void copy(const NgvRadioEnvironmentRequestVector& other);

  protected:
    bool operator==(const NgvRadioEnvironmentRequestVector&) = delete;

  public:
    NgvRadioEnvironmentRequestVector();
    NgvRadioEnvironmentRequestVector(const NgvRadioEnvironmentRequestVector& other);
    virtual ~NgvRadioEnvironmentRequestVector();
    NgvRadioEnvironmentRequestVector& operator=(const NgvRadioEnvironmentRequestVector& other);
    virtual NgvRadioEnvironmentRequestVector *dup() const override {return new NgvRadioEnvironmentRequestVector(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual NgvPpduFormat getPpduFormat() const;
    virtual void setPpduFormat(NgvPpduFormat ppduFormat);

    virtual int getNgvMcs() const;
    virtual void setNgvMcs(int ngvMcs);

    virtual int getNumSpatialStreams() const;
    virtual void setNumSpatialStreams(int numSpatialStreams);

    virtual bool getPermittedAggregation() const;
    virtual void setPermittedAggregation(bool permittedAggregation);

    virtual int getNumRepetitions() const;
    virtual void setNumRepetitions(int numRepetitions);

    virtual ::omnetpp::simtime_t getExpiryTime() const;
    virtual void setExpiryTime(::omnetpp::simtime_t expiryTime);

    virtual int getChannelNumber() const;
    virtual void setChannelNumber(int channelNumber);

    virtual int getPrimaryChannelNumber() const;
    virtual void setPrimaryChannelNumber(int primaryChannelNumber);

    virtual int getChannelWidth() const;
    virtual void setChannelWidth(int channelWidth);

    virtual double getTxPowerSpectralDensity() const;
    virtual void setTxPowerSpectralDensity(double txPowerSpectralDensity);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NgvRadioEnvironmentRequestVector& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NgvRadioEnvironmentRequestVector& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mgmt/Ieee80211BdPrimitives.msg:67</tt> by opp_msgtool.
 * <pre>
 * class MaUnitdataRequest extends cObject
 * {
 *     MacAddress receiverAddress;
 * 
 *     string msduId;
 * 
 *     NgvRadioEnvironmentRequestVector radioEnvRequestVector;
 * }
 * </pre>
 */
class INET_API MaUnitdataRequest : public ::omnetpp::cObject
{
  protected:
    ::inet::MacAddress receiverAddress;
    ::omnetpp::opp_string msduId;
    NgvRadioEnvironmentRequestVector radioEnvRequestVector;

  private:
    void copy(const MaUnitdataRequest& other);

  protected:
    bool operator==(const MaUnitdataRequest&) = delete;

  public:
    MaUnitdataRequest();
    MaUnitdataRequest(const MaUnitdataRequest& other);
    virtual ~MaUnitdataRequest();
    MaUnitdataRequest& operator=(const MaUnitdataRequest& other);
    virtual MaUnitdataRequest *dup() const override {return new MaUnitdataRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const ::inet::MacAddress& getReceiverAddress() const;
    virtual ::inet::MacAddress& getReceiverAddressForUpdate() { return const_cast<::inet::MacAddress&>(const_cast<MaUnitdataRequest*>(this)->getReceiverAddress());}
    virtual void setReceiverAddress(const ::inet::MacAddress& receiverAddress);

    virtual const char * getMsduId() const;
    virtual void setMsduId(const char * msduId);

    virtual const NgvRadioEnvironmentRequestVector& getRadioEnvRequestVector() const;
    virtual NgvRadioEnvironmentRequestVector& getRadioEnvRequestVectorForUpdate() { return const_cast<NgvRadioEnvironmentRequestVector&>(const_cast<MaUnitdataRequest*>(this)->getRadioEnvRequestVector());}
    virtual void setRadioEnvRequestVector(const NgvRadioEnvironmentRequestVector& radioEnvRequestVector);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MaUnitdataRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MaUnitdataRequest& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mgmt/Ieee80211BdPrimitives.msg:76</tt> by opp_msgtool.
 * <pre>
 * class MaUnitdataIndication extends cObject
 * {
 *     MacAddress transmitterAddress;
 * 
 *     string msduId;
 * 
 *     int channelBusyPercentage;
 * }
 * </pre>
 */
class INET_API MaUnitdataIndication : public ::omnetpp::cObject
{
  protected:
    ::inet::MacAddress transmitterAddress;
    ::omnetpp::opp_string msduId;
    int channelBusyPercentage = 0;

  private:
    void copy(const MaUnitdataIndication& other);

  protected:
    bool operator==(const MaUnitdataIndication&) = delete;

  public:
    MaUnitdataIndication();
    MaUnitdataIndication(const MaUnitdataIndication& other);
    virtual ~MaUnitdataIndication();
    MaUnitdataIndication& operator=(const MaUnitdataIndication& other);
    virtual MaUnitdataIndication *dup() const override {return new MaUnitdataIndication(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const ::inet::MacAddress& getTransmitterAddress() const;
    virtual ::inet::MacAddress& getTransmitterAddressForUpdate() { return const_cast<::inet::MacAddress&>(const_cast<MaUnitdataIndication*>(this)->getTransmitterAddress());}
    virtual void setTransmitterAddress(const ::inet::MacAddress& transmitterAddress);

    virtual const char * getMsduId() const;
    virtual void setMsduId(const char * msduId);

    virtual int getChannelBusyPercentage() const;
    virtual void setChannelBusyPercentage(int channelBusyPercentage);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MaUnitdataIndication& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MaUnitdataIndication& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mgmt/Ieee80211BdPrimitives.msg:85</tt> by opp_msgtool.
 * <pre>
 * class MaUnitdataStatusIndication extends cObject
 * {
 *     string msduId;
 *     bool success;
 * }
 * </pre>
 */
class INET_API MaUnitdataStatusIndication : public ::omnetpp::cObject
{
  protected:
    ::omnetpp::opp_string msduId;
    bool success = false;

  private:
    void copy(const MaUnitdataStatusIndication& other);

  protected:
    bool operator==(const MaUnitdataStatusIndication&) = delete;

  public:
    MaUnitdataStatusIndication();
    MaUnitdataStatusIndication(const MaUnitdataStatusIndication& other);
    virtual ~MaUnitdataStatusIndication();
    MaUnitdataStatusIndication& operator=(const MaUnitdataStatusIndication& other);
    virtual MaUnitdataStatusIndication *dup() const override {return new MaUnitdataStatusIndication(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsduId() const;
    virtual void setMsduId(const char * msduId);

    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MaUnitdataStatusIndication& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MaUnitdataStatusIndication& obj) {obj.parsimUnpack(b);}


}  // namespace ieee80211
}  // namespace inet


namespace omnetpp {

template<> inline inet::ieee80211::MlmeRadioEnvironmentRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ieee80211::MlmeRadioEnvironmentRequest*>(ptr.get<cObject>()); }
template<> inline inet::ieee80211::MlmeRadioEnvironmentIndication *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ieee80211::MlmeRadioEnvironmentIndication*>(ptr.get<cObject>()); }
template<> inline inet::ieee80211::NgvRadioEnvironmentRequestVector *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ieee80211::NgvRadioEnvironmentRequestVector*>(ptr.get<cObject>()); }
template<> inline inet::ieee80211::MaUnitdataRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ieee80211::MaUnitdataRequest*>(ptr.get<cObject>()); }
template<> inline inet::ieee80211::MaUnitdataIndication *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ieee80211::MaUnitdataIndication*>(ptr.get<cObject>()); }
template<> inline inet::ieee80211::MaUnitdataStatusIndication *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ieee80211::MaUnitdataStatusIndication*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET__IEEE80211_IEEE80211BDPRIMITIVES_M_H

