//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/linklayer/ieee80211/mgmt/NgvRadioEnvTag.msg.
//

#ifndef __INET__IEEE80211_NGVRADIOENVTAG_M_H
#define __INET__IEEE80211_NGVRADIOENVTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace ieee80211 {

class NgvRadioEnvTag;

}  // namespace ieee80211
}  // namespace inet

#include "inet/linklayer/common/MacAddress_m.h" // import inet.linklayer.common.MacAddress


namespace inet {
namespace ieee80211 {

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mgmt/NgvRadioEnvTag.msg:21</tt> by opp_msgtool.
 * <pre>
 * class NgvRadioEnvTag extends cObject
 * {
 *     int ngvMcs;
 *     int numSpatialStreams;
 *     bool permittedAggregation;
 *     int numRepetitions;
 *     double expiryTime;
 *     int channelNumber;
 *     int primaryChannelNumber;
 *     int channelWidth;
 *     double txPowerSpectralDensity;
 * }
 * </pre>
 */
class INET_API NgvRadioEnvTag : public ::omnetpp::cObject
{
  protected:
    int ngvMcs = 0;
    int numSpatialStreams = 0;
    bool permittedAggregation = false;
    int numRepetitions = 0;
    double expiryTime = 0;
    int channelNumber = 0;
    int primaryChannelNumber = 0;
    int channelWidth = 0;
    double txPowerSpectralDensity = 0;

  private:
    void copy(const NgvRadioEnvTag& other);

  protected:
    bool operator==(const NgvRadioEnvTag&) = delete;

  public:
    NgvRadioEnvTag();
    NgvRadioEnvTag(const NgvRadioEnvTag& other);
    virtual ~NgvRadioEnvTag();
    NgvRadioEnvTag& operator=(const NgvRadioEnvTag& other);
    virtual NgvRadioEnvTag *dup() const override {return new NgvRadioEnvTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getNgvMcs() const;
    virtual void setNgvMcs(int ngvMcs);

    virtual int getNumSpatialStreams() const;
    virtual void setNumSpatialStreams(int numSpatialStreams);

    virtual bool getPermittedAggregation() const;
    virtual void setPermittedAggregation(bool permittedAggregation);

    virtual int getNumRepetitions() const;
    virtual void setNumRepetitions(int numRepetitions);

    virtual double getExpiryTime() const;
    virtual void setExpiryTime(double expiryTime);

    virtual int getChannelNumber() const;
    virtual void setChannelNumber(int channelNumber);

    virtual int getPrimaryChannelNumber() const;
    virtual void setPrimaryChannelNumber(int primaryChannelNumber);

    virtual int getChannelWidth() const;
    virtual void setChannelWidth(int channelWidth);

    virtual double getTxPowerSpectralDensity() const;
    virtual void setTxPowerSpectralDensity(double txPowerSpectralDensity);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NgvRadioEnvTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NgvRadioEnvTag& obj) {obj.parsimUnpack(b);}


}  // namespace ieee80211
}  // namespace inet


namespace omnetpp {

template<> inline inet::ieee80211::NgvRadioEnvTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ieee80211::NgvRadioEnvTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET__IEEE80211_NGVRADIOENVTAG_M_H

