//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/routing/aodvSdn/AodvSdnControlPackets.msg.
//

#ifndef __INET__AODVSDN_AODVSDNCONTROLPACKETS_M_H
#define __INET__AODVSDN_AODVSDNCONTROLPACKETS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace aodvSdn {

class AodvSdnControlPacket;
class Rreq;
class Rrep;
struct UnreachableNode;
class Rerr;
class RrepAck;
class WaitForRrep;
class PacketHolderMessage;
struct SdnControllerEntry;
class Sdnadv;
struct NeighborQosEntry;
class Regreq;
struct OfpHeader;
class Regrep;

}  // namespace aodvSdn
}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {
namespace aodvSdn {

/**
 * Enum generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:15</tt> by opp_msgtool.
 * <pre>
 * enum AodvSdnControlPacketType
 * {
 *     RREQ = 1;
 *     RREP = 2;
 *     RERR = 3;
 *     RREPACK = 4;
 *     RREQ_IPv6 = 16;
 *     RREP_IPv6 = 17;
 *     RERR_IPv6 = 18;
 *     RREPACK_IPv6 = 19;
 * 
 *     SDNADV = 32;
 *     REGREQ = 33;
 *     REGREP = 34;
 * }
 * </pre>
 */
enum AodvSdnControlPacketType {
    RREQ = 1,
    RREP = 2,
    RERR = 3,
    RREPACK = 4,
    RREQ_IPv6 = 16,
    RREP_IPv6 = 17,
    RERR_IPv6 = 18,
    RREPACK_IPv6 = 19,
    SDNADV = 32,
    REGREQ = 33,
    REGREP = 34
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AodvSdnControlPacketType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AodvSdnControlPacketType& e) { int n; b->unpack(n); e = static_cast<AodvSdnControlPacketType>(n); }

/**
 * Enum generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:31</tt> by opp_msgtool.
 * <pre>
 * enum SdnNiceType
 * {
 *     NICE_NONE_OR_LEAVE = 1;
 *     NICE_BASIC_AODV = 2;
 *     NICE_AODV_QOS = 3;
 *     NICE_ADVANCED_SDN = 4;
 * }
 * </pre>
 */
enum SdnNiceType {
    NICE_NONE_OR_LEAVE = 1,
    NICE_BASIC_AODV = 2,
    NICE_AODV_QOS = 3,
    NICE_ADVANCED_SDN = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SdnNiceType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SdnNiceType& e) { int n; b->unpack(n); e = static_cast<SdnNiceType>(n); }

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:39</tt> by opp_msgtool.
 * <pre>
 * class AodvSdnControlPacket extends FieldsChunk
 * {
 *     AodvSdnControlPacketType packetType = static_cast<AodvSdnControlPacketType>(-1);
 * }
 * </pre>
 */
class INET_API AodvSdnControlPacket : public ::inet::FieldsChunk
{
  protected:
    AodvSdnControlPacketType packetType = static_cast<AodvSdnControlPacketType>(-1);

  private:
    void copy(const AodvSdnControlPacket& other);

  protected:
    bool operator==(const AodvSdnControlPacket&) = delete;

  public:
    AodvSdnControlPacket();
    AodvSdnControlPacket(const AodvSdnControlPacket& other);
    virtual ~AodvSdnControlPacket();
    AodvSdnControlPacket& operator=(const AodvSdnControlPacket& other);
    virtual AodvSdnControlPacket *dup() const override {return new AodvSdnControlPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual AodvSdnControlPacketType getPacketType() const;
    virtual void setPacketType(AodvSdnControlPacketType packetType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AodvSdnControlPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AodvSdnControlPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:44</tt> by opp_msgtool.
 * <pre>
 * class Rreq extends AodvSdnControlPacket
 * {
 *     bool joinFlag;
 *     bool repairFlag;
 *     bool gratuitousRREPFlag;
 *     bool destOnlyFlag;
 *     bool unknownSeqNumFlag;
 *     uint16_t reserved = 0;
 *     unsigned int hopCount;
 *     uint32_t rreqId;
 *     L3Address destAddr;
 *     uint32_t destSeqNum;
 *     L3Address originatorAddr;
 *     uint32_t originatorSeqNum;
 * 
 *     double deletePeriod;
 * }
 * </pre>
 */
class INET_API Rreq : public ::inet::aodvSdn::AodvSdnControlPacket
{
  protected:
    bool joinFlag = false;
    bool repairFlag = false;
    bool gratuitousRREPFlag = false;
    bool destOnlyFlag = false;
    bool unknownSeqNumFlag = false;
    uint16_t reserved = 0;
    unsigned int hopCount = 0;
    uint32_t rreqId = 0;
    ::inet::L3Address destAddr;
    uint32_t destSeqNum = 0;
    ::inet::L3Address originatorAddr;
    uint32_t originatorSeqNum = 0;
    double deletePeriod = 0;

  private:
    void copy(const Rreq& other);

  protected:
    bool operator==(const Rreq&) = delete;

  public:
    Rreq();
    Rreq(const Rreq& other);
    virtual ~Rreq();
    Rreq& operator=(const Rreq& other);
    virtual Rreq *dup() const override {return new Rreq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getJoinFlag() const;
    virtual void setJoinFlag(bool joinFlag);

    virtual bool getRepairFlag() const;
    virtual void setRepairFlag(bool repairFlag);

    virtual bool getGratuitousRREPFlag() const;
    virtual void setGratuitousRREPFlag(bool gratuitousRREPFlag);

    virtual bool getDestOnlyFlag() const;
    virtual void setDestOnlyFlag(bool destOnlyFlag);

    virtual bool getUnknownSeqNumFlag() const;
    virtual void setUnknownSeqNumFlag(bool unknownSeqNumFlag);

    virtual uint16_t getReserved() const;
    virtual void setReserved(uint16_t reserved);

    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);

    virtual uint32_t getRreqId() const;
    virtual void setRreqId(uint32_t rreqId);

    virtual const ::inet::L3Address& getDestAddr() const;
    virtual ::inet::L3Address& getDestAddrForUpdate() { handleChange();return const_cast<::inet::L3Address&>(const_cast<Rreq*>(this)->getDestAddr());}
    virtual void setDestAddr(const ::inet::L3Address& destAddr);

    virtual uint32_t getDestSeqNum() const;
    virtual void setDestSeqNum(uint32_t destSeqNum);

    virtual const ::inet::L3Address& getOriginatorAddr() const;
    virtual ::inet::L3Address& getOriginatorAddrForUpdate() { handleChange();return const_cast<::inet::L3Address&>(const_cast<Rreq*>(this)->getOriginatorAddr());}
    virtual void setOriginatorAddr(const ::inet::L3Address& originatorAddr);

    virtual uint32_t getOriginatorSeqNum() const;
    virtual void setOriginatorSeqNum(uint32_t originatorSeqNum);

    virtual double getDeletePeriod() const;
    virtual void setDeletePeriod(double deletePeriod);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Rreq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Rreq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:62</tt> by opp_msgtool.
 * <pre>
 * class Rrep extends AodvSdnControlPacket
 * {
 *     bool repairFlag;
 *     bool ackRequiredFlag;
 *     uint16_t reserved = 0;
 *     unsigned int prefixSize;
 *     unsigned int hopCount;
 *     L3Address destAddr;
 *     uint32_t destSeqNum;
 *     L3Address originatorAddr;
 *     simtime_t lifeTime;
 * }
 * </pre>
 */
class INET_API Rrep : public ::inet::aodvSdn::AodvSdnControlPacket
{
  protected:
    bool repairFlag = false;
    bool ackRequiredFlag = false;
    uint16_t reserved = 0;
    unsigned int prefixSize = 0;
    unsigned int hopCount = 0;
    ::inet::L3Address destAddr;
    uint32_t destSeqNum = 0;
    ::inet::L3Address originatorAddr;
    ::omnetpp::simtime_t lifeTime = SIMTIME_ZERO;

  private:
    void copy(const Rrep& other);

  protected:
    bool operator==(const Rrep&) = delete;

  public:
    Rrep();
    Rrep(const Rrep& other);
    virtual ~Rrep();
    Rrep& operator=(const Rrep& other);
    virtual Rrep *dup() const override {return new Rrep(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getRepairFlag() const;
    virtual void setRepairFlag(bool repairFlag);

    virtual bool getAckRequiredFlag() const;
    virtual void setAckRequiredFlag(bool ackRequiredFlag);

    virtual uint16_t getReserved() const;
    virtual void setReserved(uint16_t reserved);

    virtual unsigned int getPrefixSize() const;
    virtual void setPrefixSize(unsigned int prefixSize);

    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);

    virtual const ::inet::L3Address& getDestAddr() const;
    virtual ::inet::L3Address& getDestAddrForUpdate() { handleChange();return const_cast<::inet::L3Address&>(const_cast<Rrep*>(this)->getDestAddr());}
    virtual void setDestAddr(const ::inet::L3Address& destAddr);

    virtual uint32_t getDestSeqNum() const;
    virtual void setDestSeqNum(uint32_t destSeqNum);

    virtual const ::inet::L3Address& getOriginatorAddr() const;
    virtual ::inet::L3Address& getOriginatorAddrForUpdate() { handleChange();return const_cast<::inet::L3Address&>(const_cast<Rrep*>(this)->getOriginatorAddr());}
    virtual void setOriginatorAddr(const ::inet::L3Address& originatorAddr);

    virtual ::omnetpp::simtime_t getLifeTime() const;
    virtual void setLifeTime(::omnetpp::simtime_t lifeTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Rrep& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Rrep& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from inet/routing/aodvSdn/AodvSdnControlPackets.msg:75 by opp_msgtool.
 */
struct INET_API UnreachableNode
{
    UnreachableNode();
    ::inet::L3Address addr;
    uint32_t seqNum = 0;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const UnreachableNode& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, UnreachableNode& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UnreachableNode& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UnreachableNode& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:82</tt> by opp_msgtool.
 * <pre>
 * class Rerr extends AodvSdnControlPacket
 * {
 *     bool noDeleteFlag;
 *     uint16_t reserved = 0;
 *     UnreachableNode unreachableNodes[];
 * }
 * </pre>
 */
class INET_API Rerr : public ::inet::aodvSdn::AodvSdnControlPacket
{
  protected:
    bool noDeleteFlag = false;
    uint16_t reserved = 0;
    UnreachableNode *unreachableNodes = nullptr;
    size_t unreachableNodes_arraysize = 0;

  private:
    void copy(const Rerr& other);

  protected:
    bool operator==(const Rerr&) = delete;

  public:
    Rerr();
    Rerr(const Rerr& other);
    virtual ~Rerr();
    Rerr& operator=(const Rerr& other);
    virtual Rerr *dup() const override {return new Rerr(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getNoDeleteFlag() const;
    virtual void setNoDeleteFlag(bool noDeleteFlag);

    virtual uint16_t getReserved() const;
    virtual void setReserved(uint16_t reserved);

    virtual void setUnreachableNodesArraySize(size_t size);
    virtual size_t getUnreachableNodesArraySize() const;
    virtual const UnreachableNode& getUnreachableNodes(size_t k) const;
    virtual UnreachableNode& getUnreachableNodesForUpdate(size_t k) { handleChange();return const_cast<UnreachableNode&>(const_cast<Rerr*>(this)->getUnreachableNodes(k));}
    virtual void setUnreachableNodes(size_t k, const UnreachableNode& unreachableNodes);
    virtual void insertUnreachableNodes(size_t k, const UnreachableNode& unreachableNodes);
    [[deprecated]] void insertUnreachableNodes(const UnreachableNode& unreachableNodes) {appendUnreachableNodes(unreachableNodes);}
    virtual void appendUnreachableNodes(const UnreachableNode& unreachableNodes);
    virtual void eraseUnreachableNodes(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Rerr& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Rerr& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:89</tt> by opp_msgtool.
 * <pre>
 * class RrepAck extends AodvSdnControlPacket
 * {
 *     chunkLength = B(2);
 *     uint8_t reserved = 0;
 * }
 * </pre>
 */
class INET_API RrepAck : public ::inet::aodvSdn::AodvSdnControlPacket
{
  protected:
    uint8_t reserved = 0;

  private:
    void copy(const RrepAck& other);

  protected:
    bool operator==(const RrepAck&) = delete;

  public:
    RrepAck();
    RrepAck(const RrepAck& other);
    virtual ~RrepAck();
    RrepAck& operator=(const RrepAck& other);
    virtual RrepAck *dup() const override {return new RrepAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint8_t getReserved() const;
    virtual void setReserved(uint8_t reserved);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RrepAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RrepAck& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:95</tt> by opp_msgtool.
 * <pre>
 * message WaitForRrep
 * {
 *     L3Address destAddr;
 *     unsigned int lastTTL;
 *     bool fromInvalidEntry;
 * }
 * </pre>
 */
class INET_API WaitForRrep : public ::omnetpp::cMessage
{
  protected:
    ::inet::L3Address destAddr;
    unsigned int lastTTL = 0;
    bool fromInvalidEntry = false;

  private:
    void copy(const WaitForRrep& other);

  protected:
    bool operator==(const WaitForRrep&) = delete;

  public:
    WaitForRrep(const char *name=nullptr, short kind=0);
    WaitForRrep(const WaitForRrep& other);
    virtual ~WaitForRrep();
    WaitForRrep& operator=(const WaitForRrep& other);
    virtual WaitForRrep *dup() const override {return new WaitForRrep(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const ::inet::L3Address& getDestAddr() const;
    virtual ::inet::L3Address& getDestAddrForUpdate() { return const_cast<::inet::L3Address&>(const_cast<WaitForRrep*>(this)->getDestAddr());}
    virtual void setDestAddr(const ::inet::L3Address& destAddr);

    virtual unsigned int getLastTTL() const;
    virtual void setLastTTL(unsigned int lastTTL);

    virtual bool getFromInvalidEntry() const;
    virtual void setFromInvalidEntry(bool fromInvalidEntry);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WaitForRrep& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WaitForRrep& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:102</tt> by opp_msgtool.
 * <pre>
 * message PacketHolderMessage
 * {
 *     Packet *ownedPacket \@owned;
 * }
 * </pre>
 */
class INET_API PacketHolderMessage : public ::omnetpp::cMessage
{
  protected:
    ::inet::Packet * ownedPacket = nullptr;

  private:
    void copy(const PacketHolderMessage& other);

  protected:
    bool operator==(const PacketHolderMessage&) = delete;

  public:
    PacketHolderMessage(const char *name=nullptr, short kind=0);
    PacketHolderMessage(const PacketHolderMessage& other);
    virtual ~PacketHolderMessage();
    PacketHolderMessage& operator=(const PacketHolderMessage& other);
    virtual PacketHolderMessage *dup() const override {return new PacketHolderMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const ::inet::Packet * getOwnedPacket() const;
    virtual ::inet::Packet * getOwnedPacketForUpdate() { return const_cast<::inet::Packet *>(const_cast<PacketHolderMessage*>(this)->getOwnedPacket());}
    virtual void setOwnedPacket(::inet::Packet * ownedPacket);
    virtual ::inet::Packet * removeOwnedPacket();
    [[deprecated]] ::inet::Packet * dropOwnedPacket() {return removeOwnedPacket();}
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketHolderMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketHolderMessage& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from inet/routing/aodvSdn/AodvSdnControlPackets.msg:107 by opp_msgtool.
 */
struct INET_API SdnControllerEntry
{
    SdnControllerEntry();
    ::inet::L3Address controllerAddr;
    ::omnetpp::opp_string controllerInfo;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const SdnControllerEntry& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, SdnControllerEntry& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SdnControllerEntry& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SdnControllerEntry& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:114</tt> by opp_msgtool.
 * <pre>
 * class Sdnadv extends AodvSdnControlPacket
 * {
 *     uint8_t noOfControllers = 0;
 *     unsigned int hopCount = 1;
 *     SdnControllerEntry controllers[];
 * }
 * </pre>
 */
class INET_API Sdnadv : public ::inet::aodvSdn::AodvSdnControlPacket
{
  protected:
    uint8_t noOfControllers = 0;
    unsigned int hopCount = 1;
    SdnControllerEntry *controllers = nullptr;
    size_t controllers_arraysize = 0;

  private:
    void copy(const Sdnadv& other);

  protected:
    bool operator==(const Sdnadv&) = delete;

  public:
    Sdnadv();
    Sdnadv(const Sdnadv& other);
    virtual ~Sdnadv();
    Sdnadv& operator=(const Sdnadv& other);
    virtual Sdnadv *dup() const override {return new Sdnadv(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint8_t getNoOfControllers() const;
    virtual void setNoOfControllers(uint8_t noOfControllers);

    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);

    virtual void setControllersArraySize(size_t size);
    virtual size_t getControllersArraySize() const;
    virtual const SdnControllerEntry& getControllers(size_t k) const;
    virtual SdnControllerEntry& getControllersForUpdate(size_t k) { handleChange();return const_cast<SdnControllerEntry&>(const_cast<Sdnadv*>(this)->getControllers(k));}
    virtual void setControllers(size_t k, const SdnControllerEntry& controllers);
    virtual void insertControllers(size_t k, const SdnControllerEntry& controllers);
    [[deprecated]] void insertControllers(const SdnControllerEntry& controllers) {appendControllers(controllers);}
    virtual void appendControllers(const SdnControllerEntry& controllers);
    virtual void eraseControllers(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Sdnadv& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Sdnadv& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from inet/routing/aodvSdn/AodvSdnControlPackets.msg:121 by opp_msgtool.
 */
struct INET_API NeighborQosEntry
{
    NeighborQosEntry();
    ::inet::L3Address neighborAddr;
    uint8_t qosType = 0;
    uint8_t qosValue = 0;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const NeighborQosEntry& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, NeighborQosEntry& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NeighborQosEntry& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NeighborQosEntry& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:129</tt> by opp_msgtool.
 * <pre>
 * class Regreq extends AodvSdnControlPacket
 * {
 *     SdnNiceType nice = NICE_BASIC_AODV;
 *     unsigned int hopCount = 0;
 * 
 *     L3Address sourceAddr;
 * 
 *     uint16_t noOfNeighbors = 0;
 *     uint16_t noOfQos = 0;
 *     uint8_t typeOfQos = 0;
 * 
 *     NeighborQosEntry neighbors[];
 * }
 * </pre>
 */
class INET_API Regreq : public ::inet::aodvSdn::AodvSdnControlPacket
{
  protected:
    SdnNiceType nice = NICE_BASIC_AODV;
    unsigned int hopCount = 0;
    ::inet::L3Address sourceAddr;
    uint16_t noOfNeighbors = 0;
    uint16_t noOfQos = 0;
    uint8_t typeOfQos = 0;
    NeighborQosEntry *neighbors = nullptr;
    size_t neighbors_arraysize = 0;

  private:
    void copy(const Regreq& other);

  protected:
    bool operator==(const Regreq&) = delete;

  public:
    Regreq();
    Regreq(const Regreq& other);
    virtual ~Regreq();
    Regreq& operator=(const Regreq& other);
    virtual Regreq *dup() const override {return new Regreq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual SdnNiceType getNice() const;
    virtual void setNice(SdnNiceType nice);

    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);

    virtual const ::inet::L3Address& getSourceAddr() const;
    virtual ::inet::L3Address& getSourceAddrForUpdate() { handleChange();return const_cast<::inet::L3Address&>(const_cast<Regreq*>(this)->getSourceAddr());}
    virtual void setSourceAddr(const ::inet::L3Address& sourceAddr);

    virtual uint16_t getNoOfNeighbors() const;
    virtual void setNoOfNeighbors(uint16_t noOfNeighbors);

    virtual uint16_t getNoOfQos() const;
    virtual void setNoOfQos(uint16_t noOfQos);

    virtual uint8_t getTypeOfQos() const;
    virtual void setTypeOfQos(uint8_t typeOfQos);

    virtual void setNeighborsArraySize(size_t size);
    virtual size_t getNeighborsArraySize() const;
    virtual const NeighborQosEntry& getNeighbors(size_t k) const;
    virtual NeighborQosEntry& getNeighborsForUpdate(size_t k) { handleChange();return const_cast<NeighborQosEntry&>(const_cast<Regreq*>(this)->getNeighbors(k));}
    virtual void setNeighbors(size_t k, const NeighborQosEntry& neighbors);
    virtual void insertNeighbors(size_t k, const NeighborQosEntry& neighbors);
    [[deprecated]] void insertNeighbors(const NeighborQosEntry& neighbors) {appendNeighbors(neighbors);}
    virtual void appendNeighbors(const NeighborQosEntry& neighbors);
    virtual void eraseNeighbors(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Regreq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Regreq& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from inet/routing/aodvSdn/AodvSdnControlPackets.msg:143 by opp_msgtool.
 */
struct INET_API OfpHeader
{
    OfpHeader();
    uint8_t version = 0;
    uint8_t type = 0;
    uint16_t length = 0;
    uint32_t xid = 0;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const OfpHeader& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, OfpHeader& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OfpHeader& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OfpHeader& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>inet/routing/aodvSdn/AodvSdnControlPackets.msg:152</tt> by opp_msgtool.
 * <pre>
 * class Regrep extends AodvSdnControlPacket
 * {
 *     SdnNiceType nice = NICE_BASIC_AODV;
 *     unsigned int hopCount = 0;
 * 
 *     OfpHeader ofpHeader;
 *     uint8_t ofpData[];
 * }
 * </pre>
 */
class INET_API Regrep : public ::inet::aodvSdn::AodvSdnControlPacket
{
  protected:
    SdnNiceType nice = NICE_BASIC_AODV;
    unsigned int hopCount = 0;
    OfpHeader ofpHeader;
    uint8_t *ofpData = nullptr;
    size_t ofpData_arraysize = 0;

  private:
    void copy(const Regrep& other);

  protected:
    bool operator==(const Regrep&) = delete;

  public:
    Regrep();
    Regrep(const Regrep& other);
    virtual ~Regrep();
    Regrep& operator=(const Regrep& other);
    virtual Regrep *dup() const override {return new Regrep(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual SdnNiceType getNice() const;
    virtual void setNice(SdnNiceType nice);

    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);

    virtual const OfpHeader& getOfpHeader() const;
    virtual OfpHeader& getOfpHeaderForUpdate() { handleChange();return const_cast<OfpHeader&>(const_cast<Regrep*>(this)->getOfpHeader());}
    virtual void setOfpHeader(const OfpHeader& ofpHeader);

    virtual void setOfpDataArraySize(size_t size);
    virtual size_t getOfpDataArraySize() const;
    virtual uint8_t getOfpData(size_t k) const;
    virtual void setOfpData(size_t k, uint8_t ofpData);
    virtual void insertOfpData(size_t k, uint8_t ofpData);
    [[deprecated]] void insertOfpData(uint8_t ofpData) {appendOfpData(ofpData);}
    virtual void appendOfpData(uint8_t ofpData);
    virtual void eraseOfpData(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Regrep& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Regrep& obj) {obj.parsimUnpack(b);}


}  // namespace aodvSdn
}  // namespace inet


namespace omnetpp {

template<> inline inet::aodvSdn::AodvSdnControlPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::AodvSdnControlPacket*>(ptr.get<cObject>()); }
template<> inline inet::aodvSdn::Rreq *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::Rreq*>(ptr.get<cObject>()); }
template<> inline inet::aodvSdn::Rrep *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::Rrep*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::aodvSdn::UnreachableNode *p) {return any_ptr(p);}
template<> inline inet::aodvSdn::UnreachableNode *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::aodvSdn::UnreachableNode>(); }
template<> inline inet::aodvSdn::Rerr *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::Rerr*>(ptr.get<cObject>()); }
template<> inline inet::aodvSdn::RrepAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::RrepAck*>(ptr.get<cObject>()); }
template<> inline inet::aodvSdn::WaitForRrep *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::WaitForRrep*>(ptr.get<cObject>()); }
template<> inline inet::aodvSdn::PacketHolderMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::PacketHolderMessage*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::aodvSdn::SdnControllerEntry *p) {return any_ptr(p);}
template<> inline inet::aodvSdn::SdnControllerEntry *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::aodvSdn::SdnControllerEntry>(); }
template<> inline inet::aodvSdn::Sdnadv *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::Sdnadv*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::aodvSdn::NeighborQosEntry *p) {return any_ptr(p);}
template<> inline inet::aodvSdn::NeighborQosEntry *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::aodvSdn::NeighborQosEntry>(); }
template<> inline inet::aodvSdn::Regreq *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::Regreq*>(ptr.get<cObject>()); }
inline any_ptr toAnyPtr(const inet::aodvSdn::OfpHeader *p) {return any_ptr(p);}
template<> inline inet::aodvSdn::OfpHeader *fromAnyPtr(any_ptr ptr) { return ptr.get<inet::aodvSdn::OfpHeader>(); }
template<> inline inet::aodvSdn::Regrep *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::aodvSdn::Regrep*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET__AODVSDN_AODVSDNCONTROLPACKETS_M_H

