//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/linklayer/ieee80211/mac/ngv/NgvExpiryDeadlineTag.msg.
//

#ifndef __INET_NGVEXPIRYDEADLINETAG_M_H
#define __INET_NGVEXPIRYDEADLINETAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class NgvExpiryDeadlineTag;

}  // namespace inet

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace inet {

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mac/ngv/NgvExpiryDeadlineTag.msg:21</tt> by opp_msgtool.
 * <pre>
 * class NgvExpiryDeadlineTag extends TagBase
 * {
 *     simtime_t deadline;
 * }
 * </pre>
 */
class INET_API NgvExpiryDeadlineTag : public ::inet::TagBase
{
  protected:
    ::omnetpp::simtime_t deadline = SIMTIME_ZERO;

  private:
    void copy(const NgvExpiryDeadlineTag& other);

  protected:
    bool operator==(const NgvExpiryDeadlineTag&) = delete;

  public:
    NgvExpiryDeadlineTag();
    NgvExpiryDeadlineTag(const NgvExpiryDeadlineTag& other);
    virtual ~NgvExpiryDeadlineTag();
    NgvExpiryDeadlineTag& operator=(const NgvExpiryDeadlineTag& other);
    virtual NgvExpiryDeadlineTag *dup() const override {return new NgvExpiryDeadlineTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getDeadline() const;
    virtual void setDeadline(::omnetpp::simtime_t deadline);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NgvExpiryDeadlineTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NgvExpiryDeadlineTag& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::NgvExpiryDeadlineTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::NgvExpiryDeadlineTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_NGVEXPIRYDEADLINETAG_M_H

