//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/linklayer/ieee80211/mac/ngv/NgvRadioEnvironmentReqTag.msg.
//

#ifndef __INET_NGVRADIOENVIRONMENTREQTAG_M_H
#define __INET_NGVRADIOENVIRONMENTREQTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class NgvRadioEnvironmentReqTag;

}  // namespace inet

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace inet {

/**
 * Class generated from <tt>inet/linklayer/ieee80211/mac/ngv/NgvRadioEnvironmentReqTag.msg:25</tt> by opp_msgtool.
 * <pre>
 * class NgvRadioEnvironmentReqTag extends TagBase
 * {
 *     bool ppduFormatPresent;
 *     int ppduFormat; // 0: NON_NGV, 1: NGV
 * 
 *     bool mcsPresent;
 *     int ngvMcs;
 *     double dataRateMbps;
 * 
 *     bool nssPresent;
 *     int numSpatialStreams;
 * 
 *     bool aggregationPresent;
 *     bool permittedAggregation;
 * 
 *     bool repetitionPresent;
 *     int numRepetitions;
 * 
 *     bool expiryPresent;
 *     double expiryTime;
 * 
 *     bool channelPresent;
 *     int channelNumber;
 * 
 *     bool primaryChannelPresent;
 *     int primaryChannelNumber;
 * 
 *     bool channelWidthPresent;
 *     int channelWidthMHz; // 10 or 20
 * }
 * </pre>
 */
class INET_API NgvRadioEnvironmentReqTag : public ::inet::TagBase
{
  protected:
    bool ppduFormatPresent = false;
    int ppduFormat = 0;
    bool mcsPresent = false;
    int ngvMcs = 0;
    double dataRateMbps = 0;
    bool nssPresent = false;
    int numSpatialStreams = 0;
    bool aggregationPresent = false;
    bool permittedAggregation = false;
    bool repetitionPresent = false;
    int numRepetitions = 0;
    bool expiryPresent = false;
    double expiryTime = 0;
    bool channelPresent = false;
    int channelNumber = 0;
    bool primaryChannelPresent = false;
    int primaryChannelNumber = 0;
    bool channelWidthPresent = false;
    int channelWidthMHz = 0;

  private:
    void copy(const NgvRadioEnvironmentReqTag& other);

  protected:
    bool operator==(const NgvRadioEnvironmentReqTag&) = delete;

  public:
    NgvRadioEnvironmentReqTag();
    NgvRadioEnvironmentReqTag(const NgvRadioEnvironmentReqTag& other);
    virtual ~NgvRadioEnvironmentReqTag();
    NgvRadioEnvironmentReqTag& operator=(const NgvRadioEnvironmentReqTag& other);
    virtual NgvRadioEnvironmentReqTag *dup() const override {return new NgvRadioEnvironmentReqTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getPpduFormatPresent() const;
    virtual void setPpduFormatPresent(bool ppduFormatPresent);

    virtual int getPpduFormat() const;
    virtual void setPpduFormat(int ppduFormat);

    virtual bool getMcsPresent() const;
    virtual void setMcsPresent(bool mcsPresent);

    virtual int getNgvMcs() const;
    virtual void setNgvMcs(int ngvMcs);

    virtual double getDataRateMbps() const;
    virtual void setDataRateMbps(double dataRateMbps);

    virtual bool getNssPresent() const;
    virtual void setNssPresent(bool nssPresent);

    virtual int getNumSpatialStreams() const;
    virtual void setNumSpatialStreams(int numSpatialStreams);

    virtual bool getAggregationPresent() const;
    virtual void setAggregationPresent(bool aggregationPresent);

    virtual bool getPermittedAggregation() const;
    virtual void setPermittedAggregation(bool permittedAggregation);

    virtual bool getRepetitionPresent() const;
    virtual void setRepetitionPresent(bool repetitionPresent);

    virtual int getNumRepetitions() const;
    virtual void setNumRepetitions(int numRepetitions);

    virtual bool getExpiryPresent() const;
    virtual void setExpiryPresent(bool expiryPresent);

    virtual double getExpiryTime() const;
    virtual void setExpiryTime(double expiryTime);

    virtual bool getChannelPresent() const;
    virtual void setChannelPresent(bool channelPresent);

    virtual int getChannelNumber() const;
    virtual void setChannelNumber(int channelNumber);

    virtual bool getPrimaryChannelPresent() const;
    virtual void setPrimaryChannelPresent(bool primaryChannelPresent);

    virtual int getPrimaryChannelNumber() const;
    virtual void setPrimaryChannelNumber(int primaryChannelNumber);

    virtual bool getChannelWidthPresent() const;
    virtual void setChannelWidthPresent(bool channelWidthPresent);

    virtual int getChannelWidthMHz() const;
    virtual void setChannelWidthMHz(int channelWidthMHz);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NgvRadioEnvironmentReqTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NgvRadioEnvironmentReqTag& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::NgvRadioEnvironmentReqTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::NgvRadioEnvironmentReqTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_NGVRADIOENVIRONMENTREQTAG_M_H

